Y_as = [ 99.15 99.23 99.88 98.59; 72.27 66.53 100 49.85; 64.29 66.68 68.86 64.64 ] ;
X_as = categorical({'SVM (Gaussian)', 'SVM (Linear Kernel)', 'Logistic Regression',});
HB = bar(X_as , Y_as , 'group');
l = cell(1,4);
l{1}='Accuracy'; l{2}='F1'; l{3}='Precision'; l{4}='Recall';    
legend(HB,l);
ylabel('Percentage','FontSize',20,'FontWeight','bold','FontName','Times New Roman');
xlabel('Classification Techniques','FontSize',20,'FontWeight','bold','FontName','Times New Roman');
grid on;
box on;
ax = gca;
ax.FontSize = 20;
ax.FontWeight = 'bold';
ax.FontName = 'Times New Roman';
%title('Comparison of Evaluation for Transport Layer (TCP)','FontSize',12,'FontWeight','bold','FontName','Times New Roman');